from celery import Celery
from celery.utils.log import get_task_logger
import redis as redis_client
import json
import asyncio
from uuid import uuid4
from datetime import datetime, timezone

from core.config import get_settings
from core.logging import get_logger, job_id_var

settings = get_settings()
logger = get_task_logger(__name__)

celery = Celery(
    "aippt",
    broker=settings.redis_url,
    backend=settings.redis_url,
)

celery.conf.update(
    task_serializer="json",
    result_serializer="json",
    accept_content=["json"],
    task_track_started=True,
    task_acks_late=True,               # Only ack AFTER task completes — prevents loss on crash
    worker_prefetch_multiplier=1,       # One task per worker — prevents starvation
    worker_concurrency=4,              # Explicit — do not leave as default
    task_soft_time_limit=180,          # 3 min soft limit — triggers SoftTimeLimitExceeded
    task_time_limit=240,               # 4 min hard limit — kills the worker process
    task_default_rate_limit="10/m",    # Per-worker rate limit
    result_expires=3600,               # Jobs stuck in "generating" auto-expire after 1h
    broker_connection_retry_on_startup=True,
)

redis = redis_client.Redis.from_url(settings.redis_url, decode_responses=True)


def publish_ws_event(job_id: str, event: dict) -> None:
    """
    Publish event to Redis pub/sub channel AND persist to ws_events table
    for reconnection catch-up.
    Channel: ws:job:{job_id}
    """
    event_str = json.dumps(event)

    # Pub/sub: delivers to currently connected WebSocket subscribers
    redis.publish(f"ws:job:{job_id}", event_str)

    # Persistence: allows reconnecting clients to catch up on missed events
    # Stored with TTL — cleanup happens via the SQL function in init.sql
    redis.lpush(f"ws:events:{job_id}", event_str)
    redis.expire(f"ws:events:{job_id}", 7200)  # 2-hour TTL


@celery.task(
    bind=True,
    name="generate_presentation",
    max_retries=3,
    default_retry_delay=5,
)
def generate_presentation_task(
    self,
    job_id: str,
    request: dict,
    tenant_id: str | None = None,
    doc_ids: list[str] | None = None,
) -> dict:
    """
    Main generation task. Runs the 4-step AI pipeline.

    ARCHITECTURE NOTE:
    job_id is pre-generated by the API router (str(uuid4())) and passed as
    a positional argument. Celery is instructed to use this as its task ID
    via task_id=job_id in apply_async(). This eliminates the chicken-and-egg
    problem of needing the task ID before the task exists.

    Args:
        job_id: Pre-generated UUID, also the Celery task ID
        request: {
            prompt, theme, narrative_framework, industry_vertical,
            language, audience, client_request_id
        }
    """
    # Bind job_id to logging context for this worker
    token = job_id_var.set(job_id)

    redis.hset(f"job:{job_id}", mapping={
        "status": "generating",
        "started_at": datetime.now(timezone.utc).isoformat(),
        "step": "1",
        "prompt": request.get("prompt", "")[:500],  # Truncate — do not log full prompt
    })

    publish_ws_event(job_id, {
        "type": "generation_started",
        "job_id": job_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    })

    try:
        from services.orchestration.pipeline import run_pipeline

        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            deck = loop.run_until_complete(
                run_pipeline(job_id, request, publish_ws_event, tenant_id=tenant_id, doc_ids=doc_ids)
            )
        finally:
            loop.close()

        redis.hset(f"job:{job_id}", mapping={
            "status": "complete",
            "completed_at": datetime.now(timezone.utc).isoformat(),
            "step": "done",
        })
        redis.expire(f"job:{job_id}", 3600)

        publish_ws_event(job_id, {
            "type": "generation_complete",
            "job_id": job_id,
            "deck": deck,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        })

        # Persist to PostgreSQL
        loop3 = asyncio.new_event_loop()
        asyncio.set_event_loop(loop3)
        try:
            loop3.run_until_complete(_persist_deck(deck, request))
        finally:
            loop3.close()

        return {"status": "complete", "presentation_id": deck["presentation_id"]}

    except Exception as exc:
        logger.error("pipeline_failed", job_id=job_id, error=str(exc), exc_info=True)

        partial = redis.hget(f"job:{job_id}", "slides_completed")
        status = "partial_failure" if partial and int(partial) > 0 else "failed"

        redis.hset(f"job:{job_id}", mapping={
            "status": status,
            "error": str(exc)[:500],
            "failed_at": datetime.now(timezone.utc).isoformat(),
        })
        redis.expire(f"job:{job_id}", 3600)

        publish_ws_event(job_id, {
            "type": "generation_failed",
            "job_id": job_id,
            "status": status,
            "error": str(exc)[:200],
            "timestamp": datetime.now(timezone.utc).isoformat(),
        })

        if self.request.retries < self.max_retries:
            raise self.retry(exc=exc, countdown=5 * (2 ** self.request.retries))

        # All retries exhausted — dead letter queue
        redis.lpush("dlq:failed_jobs", json.dumps({
            "job_id": job_id,
            "request": {k: v for k, v in request.items() if k != "prompt"},
            "prompt_length": len(request.get("prompt", "")),
            "error": str(exc),
            "retries": self.request.retries,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }))
        redis.expire("dlq:failed_jobs", 86400)  # 24h TTL on DLQ

        return {"status": status, "error": str(exc)}

    finally:
        job_id_var.reset(token)


async def _persist_deck(deck: dict, request: dict) -> None:
    """Save completed deck + cost metadata to PostgreSQL."""
    from services.db.session import get_db_session
    from services.db.models import Deck

    async with get_db_session() as session:
        db_deck = Deck(
            presentation_id=deck["presentation_id"],
            job_id=deck["generation_metadata"]["job_id"],
            client_request_id=request.get("client_request_id"),
            generation_status="complete",
            schema_version=deck["schema_version"],
            deck_json=deck,
            total_input_tokens=deck.get("_cost_metadata", {}).get("total_input_tokens", 0),
            total_output_tokens=deck.get("_cost_metadata", {}).get("total_output_tokens", 0),
            estimated_cost_usd=deck.get("_cost_metadata", {}).get("estimated_cost_usd", 0),
        )
        session.add(db_deck)
        await session.commit()
